name: HTML Checks Default

on:
  push:
    paths:
      - '**.html'
  pull_request:
    paths:
      - '**.html'

jobs:

  file_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check if HTML files are not empty
        run: |
          for file in app/templates/*.html; do
            if [ ! -s "$file" ]; then
              echo "Error: HTML file $file is empty!" && exit 1
            fi
          done
          echo "All HTML files are non-empty."

      - name: Check if HTML files already exist
        run: |
          for file in app/templates/*.html; do
            filename=$(basename "$file")
            if git ls-files --error-unmatch "app/templates/$filename" > /dev/null 2>&1; then
              echo "Error: File with the same name $filename already exists!" && exit 1
            fi
          done
          echo "No duplicate HTML file names detected."

  html-checks:
    runs-on: ubuntu-latest

    services:
      flask:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
          - 5000:80
        env:
          MODULE_NAME: app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install djlint html5validator linkchecker requests beautifulsoup4 flask

    - name: Run djlint (HTML/Jinja2 linter)
      run: |
        djlint app/templates/ --check --extension=html,jinja

    - name: Static files existence check
      run: python .github/scripts/check_static_files.py



