name: HTML Checks Default

on:
  push:
    paths:
      - '**.html'
  pull_request:
    paths:
      - '**.html'

jobs:
  html-checks:
    runs-on: ubuntu-latest

    services:
      flask:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
          - 5000:80
        env:
          MODULE_NAME: app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install djlint html5validator linkchecker requests beautifulsoup4 flask

    - name: Run djlint (HTML/Jinja2 linter)
      run: |
        djlint app/templates/ --check --extension=html,jinja

    - name: Static files existence check
      run: python .github/scripts/check_static_files.py

link_checker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Run LinkChecker
      run: linkchecker http://localhost:5000

