name: HTML Checks Default

on:
  push:
    paths:
      - '**.html'
  pull_request:
    paths:
      - '**.html'

jobs:
  html-checks:
    runs-on: ubuntu-latest

    services:
      flask:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
          - 5000:80
        env:
          MODULE_NAME: app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install djlint html5validator linkchecker requests beautifulsoup4 flask

    - name: Run djlint (HTML/Jinja2 linter)
      run: |
        djlint app/templates/ --check --extension=html,jinja

    - name: Run html5validator (HTML5 validation)
      run: |
        html5validator --root app/templates/ --ignore 'Element “head” is missing a required instance of child element “title”' \
          --ignore 'Bad value.*for attribute.*' \
          --ignore 'The "main" element must not appear as a descendant of the "section" element' \
          --ignore 'Stray end tag "head"' \
          --ignore 'Start tag "body" seen but an element of the same type was already open'

    - name: Check links in templates
      run: |
        linkchecker app/templates/

    - name: Static files existence check
      run: python .github/scripts/check_static_files.py

